version: '3.4'
services:

  codegen:
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    
    volumes:
      - ..:/onchain-shard:cached
      - ~/.ssh:/root/host-ssh:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.kube/config:/root/kube-config:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    working_dir: /onchain-shard